spring:
  datasource:
    url: jdbc:mysql://localhost:3306/insurance_db
    username: root
    password: zero
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: admin